index:
  path: /dashboard/cities
  controller: Selene\Modules\CityModule\Http\Controllers\CityController@index
  methods:
    - GET
  permission: CityModule

sort:
  path: /dashboard/cities/sort
  controller: Selene\Modules\CityModule\Http\Controllers\CityController@sort
  methods:
    - GET
  permission: CityModule.edit

create:
  path: /dashboard/cities/create
  controller: Selene\Modules\CityModule\Http\Controllers\CityController@create
  methods:
    - GET
  permission: CityModule.add

edit:
  path: /dashboard/cities/{{city}}/edit
  controller: Selene\Modules\CityModule\Http\Controllers\CityController@edit
  methods:
    - GET
  permission: CityModule.edit
